(lang dune 3.20)

(name arith)

(using menhir 2.1)

(generate_opam_files true)

(source
 (github shusoyo/tapl-impl))

(authors "Author Name <author@example.com>")

(package
 (name arith)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
